### ISSUE TITLE
Old c

### ISSUE THREAD

**Issue by limelect** [WouterVanNifterick/C-To-Delphi#3]
Can i send the developer a bunch of old c
simple c most do not translate.
limelect at gmail dot com

**Comment by WouterVanNifterick** [comment]
If you have some specific files that are problematic, or if you find specific issues, just send them so I can try to fix whatever is not working.

Function macro's for the pre-processor are not expanded. So code that relies heavily on macros usually doesn't translate well. I'm looking into implementing a c-preprocessor..
